# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "关于我"
  url = "#about"
  weight = 10

[[main]]
  name = "博客"
  url = "#posts"
  weight = 20

[[main]]
  name = "开源项目"
  url = "#projects"
  weight = 30

[[main]]
  name = "联系我"
  url = "#contact"
  weight = 60

[[main]]
  name = "简历"
  url = "https://hongliang-wei.netlify.app/post/example-post/"
  weight = 50


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
